#!/usr/bin/env zsh

cask_exists() {
  if ! brew cask info "${1}" | grep "Not installed" > /dev/null; then
    printf "%s already installed.\n" "$1"
    return 0
  fi

  e_warn "Missing App: $1"
  return 1
}

install_casks() {
  if $no_apps; then
    e_info "Skipping App installs"
  else
    e_info "Checking for desired Apps"

    local -a missing_apps
    local -a desired_apps

    desired_apps=(
      'google-chrome'
      'google-chrome-canary'
      'firefox'
      'imageoptim'
      'iterm2'
      'sublime-text'
      'rdio'
      'spectacle'
      'alfred'
      # 'codekit'
      'dropbox'
    )

    for i in $desired_apps; do
      if ! cask_exists $i; then
        missing_apps+=("$i")
      fi
    done

    if [[ -n "$missing_apps" ]]; then
      e_info "Installing missing Apps"

      for i in $missing_apps; do
        # Install missing Apps
        brew cask install $i
      done
    fi

    [ $? ] && e_done
  fi
}
