#!/usr/bin/env zsh

# Test whether a Homebrew repo is already tapped
# $1 - formula name
tap_exists() {
  if echo $brew_taplist | grep "$1" > /dev/null; then
    printf "%s already tapped.\n" "$1"
    return 0
  fi

  e_warn "Missing Tap: $1"
  return 1
}

# Test whether a Homebrew formula is already installed
# $1 - formula name (may include options)
formula_exists() {
  if echo $brew_formulae | grep "$1" > /dev/null; then
    printf "%s already installed.\n" "$1"
    return 0
  fi

  e_warn "Missing formula: $1"
  return 1
}

init_brew() {
  # Check for Homebrew
  if command_exists brew; then

    brew_taplist=$(brew tap 2> /dev/null)
    brew_formulae=$(brew list 2> /dev/null)

    # Update Homebrew
    e_info "Updating Homebrew"
    brew update
    [ $? ] && e_done

    # Upgrade Homebrew
    e_info "Upgrading Homebrew"
    brew upgrade
    [ $? ] && e_done

    # Tap repositorys
    e_info "Check for missing repositorys"

    local -a missing_taps
    local -a desired_taps

    desired_taps=(
      "homebrew/dupes" # more recent versions of basic os x commands
      "josegonzalez/php" # for php54
      "caskroom/cask" # for brew cask
    )

    for i in $desired_taps; do
      if ! tap_exists $i; then
        missing_taps+=("$i")
      fi
    done

    if [[ -n $missing_taps ]]; then
      e_info "Tapping required Homebrew repositorys"

      for i in $missing_taps; do
        # Tap all missing repos
        brew tap $i
      done
    fi
    [ $? ] && e_done

    # Install formulae

    e_info "Checking status of desired Homebrew formulae"

    local list_formulae
    local -a missing_formulae
    local -a desired_formulae

    desired_formulae=(
      'ack'
      'bash' # Bash 4
      'coreutils' # GNU
      'fasd'
      'figlet'
      'gource'
      'graphicsmagick'
      'imagemagick'
      'jpeg'
      'mackup'
      'neovim'
      'optipng'
      'pngcrush'
      'pngquant'
      'rsync'
      'tmux'
      'tree'
      'unrar'
      'wget --enable-iri'
      'zsh' # Zsh
      # 'brew-cask' # Installer for Apps
      # 'macvim --override-system-vim'
      # 'mariadb'
      # 'phantomjs'
      # 'php55-mcrypt'
      # 'php55-memcached'
      # 'php55-mongo'
      # 'php55-xdebug'
      # 'php56' # PHP 5.6
    )

    for i in $desired_formulae; do
      if ! formula_exists ${i[(w)1]}; then
        # Store the name (and options) of every missing formula
        missing_formulae+=("$i")
      fi
    done

    [ $? ] && e_done

    if [[ -n "$missing_formulae" ]]; then
      # Convert the array of missing formula into a list of space-separate strings
      list_formulae=$( printf "%s " $missing_formulae )

      e_info "Installing missing Homebrew formulae"
      # Install all missing formulae
      brew install $( printf $list_formulae )

      [ $? ] && e_done
    fi

    source "$DOTFILES_PATH/brew/casks"
    install_casks

    # Cleanup
    e_info "Cleaning up Brew"

    unset brew_taplist brew_formulae
    # Remove outdated versions from the Cellar
    brew cleanup

    [ $? ] && e_done
  else
    printf "\n"
    e_error "Homebrew not found.\n Aborting"
    exit
  fi
}
