#!/usr/bin/env zsh

# Test whether a Homebrew repo is already tapped
# $1 - formula name
tap_exists() {
  if echo $brew_taplist | grep "$1" > /dev/null; then
    printf "%s already tapped.\n" "$1"
    return 0
  fi

  e_warn "Missing Tap: $1"
  return 1
}

tap_repos() {
  # Tap repositorys
  e_info "Check for missing repositorys"

  brew_taplist=$(brew tap 2> /dev/null)
  local -a missing_taps
  local -a desired_taps

  desired_taps=(
    "homebrew/dupes" # more recent versions of basic os x commands
    "josegonzalez/php" # for php54
    "caskroom/cask" # for brew cask
  )

  for i in $desired_taps; do
    if ! tap_exists $i; then
      missing_taps+=("$i")
    fi
  done

  if [[ -n $missing_taps ]]; then
    e_info "Tapping required Homebrew repositorys"

    for i in $missing_taps; do
      # Tap all missing repos
      brew tap $i
    done
  fi

  unset brew_taplist

  [ $? ] && e_done
}
