#!/usr/bin/env zsh

e_info "Checking for XCode, RVM, Homebrew and Git"

# XCode
if ! command_exists gcc; then
    e_error "The XCode Command Line Tools must be installed.${NC}\n  Download: https://developer.apple.com/downloads/\n  Then run 'zsh ~/.dotfiles/bin/installer.zsh'"
fi

# Homebrew
if ! command_exists brew; then
    e_info "Installing Homebrew..."
    ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
fi

# Git
if ! command_exists git; then
    e_info "Installing Git..."
    brew update
    brew install git
fi

# RVM
if ! command_exists rvm; then
    e_info "Installing RVM..."
    curl -sSL https://get.rvm.io | bash -s stable --rails --auto-dotfiles
    source "${ZDOTDIR:-$HOME}/.rvm/scripts/rvm"
fi

# NVM
if ! command_exists nvm; then
    e_info "Installing Node Version Manager..."
    brew install nvm
    export NVM_DIR="${ZDOTDIR:-$HOME}/.nvm"
    source "$(brew --prefix nvm)/nvm.sh"
    nvm install iojs-v2.5.0
    nvm alias default iojs-v2.5.0
fi

e_done "Done"
