#!/usr/bin/zsh

e_info "Checking for XCode, Homebrew and Git"

# XCode
if (( ! $+commands[gcc] )); then
    e_error "The XCode Command Line Tools must be installed.${NC}\n  Download: https://developer.apple.com/downloads/\n  Then run 'zsh ~/.dotfiles/bin/installer.zsh'"
fi

# Homebrew
if (( ! $+commands[brew] )); then
    e_info "Installing Homebrew..."
    ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
fi

# Git
if (( ! $+commands[git] )); then
    e_info "Installing Git..."
    brew update
    brew install git
fi

[ $? ] && e_done