#!/usr/bin/env zsh

function init_git {

    if ! $( git rev-parse --is-inside-work-tree &> /dev/null ); then
        # Initialize the git repository if it's missing
        e_info "Initializing git repository"

        git init
        git remote add origin "$base_git"
        git fetch origin master
        # Reset the index and working tree to the fetched HEAD
        # (submodules are cloned in the subsequent sync step)
        git reset --hard FETCH_HEAD
        # Remove any untracked files
        git clean -fd

        [ $? ] && e_done "Done"
    fi

}


function sync_git {

    # Sync with remote repository
    e_info "Updating dotfiles"
    # Pull down the latest changes
    git pull --rebase origin master
    # Update submodules
    e_info "Updating submodules"
    git submodule update --recursive --init --quiet

    [ $? ] && e_done "Done"
}


function link_git {

    # e_info "Linking .gitfiles"

    if [ -e "${ZDOTDIR:-$HOME}/.gitattributes" ]; then
        rm "${ZDOTDIR:-$HOME}/.gitattributes"
    fi
    if [ -e "${ZDOTDIR:-$HOME}/.gitconfig" ]; then
        rm "${ZDOTDIR:-$HOME}/.gitconfig"
    fi
    if [ -e "${ZDOTDIR:-$HOME}/.gitignore" ]; then
        rm "${ZDOTDIR:-$HOME}/.gitignore"
    fi
    if [ -e "${ZDOTDIR:-$HOME}/.gitmessage" ]; then
        rm "${ZDOTDIR:-$HOME}/.gitmessage"
    fi

    link "$base_dir/rc/.gitattributes" ".gitattributes"
    link "$base_dir/rc/.gitconfig" ".gitconfig"
    link "$base_dir/rc/.gitignore" ".gitignore"
    link "$base_dir/rc/.gitmessage" ".gitmessage"

    # [ $? ] && e_done "Done"

}


function create_gitconfig {

    if [[ ! -a "${ZDOTDIR:-$HOME}/.gitconfig.user" ]]; then

        e_info "Creating gitconfig.user"
        # Create user gitconfig
        local gitconfiguser="${ZDOTDIR:-$HOME}/.gitconfig.user"
        local gitemail=
        local gitname=
        touch gitconfiguser

        vared -h -p "Enter your github user.name: " gitname
        vared -h -p "Enter your github user.email: " gitemail

        cat > "$gitconfiguser" <<EOT
[user]
    name = $gitname
    email = $gitemail
EOT
        e_info "successfully created ~/.gitconfig.user"
        # Cleanup
        unset gitconfiguser gitemail gitname

        [ $? ] && e_done "Done"
        return 0
    fi

}
