#!/usr/bin/env zsh

init_npm() {

    # Check for npm
    if command_exists 'npm'; then

        npm_list=$(npm list -g 2> /dev/null)

        # ======================================================================
        # Update npm packages
        # ======================================================================

        e_info "Updating Node.js Packages..."
        # Update npm packages globally and quietly
        npm update --global --quiet
        [ $? ] && e_done "Done"

        # ======================================================================
        # Install packages
        # ======================================================================

        e_info "Installing missing Node.js Packages..."

        local packages
        local -a missing_packages
        local -a desired_packages

        # List of npm packages
        desired_packages=(
            'bower'
            'grunt-cli'
            'gulp'
            'ios-sim'
            'ios-deploy'
            'ionic'
            'cordova'
            'phonegap'
            'coffee-script'
            'js2coffee'
            'yo'
            'jshint'
            'csslint'
            'coffeelint'
        )

        for i in $desired_packages; do
            if ! npm_exists "${i[(w)1]}"; then
                missing_packages+=("$i")
            fi
        done


        if [[ -n $missing_packages ]]; then
            # packages=$( printf "%s " $missing_packages )

            # Install packages globally
            npm install --global --quiet "$( printf "%s " "$missing_packages" )"
        fi

        [ $? ] && e_done "Done"

        # ======================================================================
        # Cleanup
        # ======================================================================

        unset npm_list
    else
        printf "\n"
        e_error "Error: npm not found."
        printf "Aborting...\n"
        exit
    fi

}
