#!/usr/bin/env zsh

source ~/.zplug/init.zsh

#
# - PLUGINS
#

zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"

zplug "plugins/git", from:oh-my-zsh, if:"which git"
zplug "plugins/git-flow", from:oh-my-zsh, if:"which git"
zplug "unixorn/git-extra-commands", from:oh-my-zsh
zplug "plugins/colored-man-pages", from:oh-my-zsh
zplug "plugins/command-no-found", from:oh-my-zsh
zplug "plugins/fasd", from:oh-my-zsh
zplug "plugins/history", from:oh-my-zsh
zplug "plugins/tmux", from:oh-my-zsh
zplug "plugins/cp", from:oh-my-zsh
zplug "plugins/nvm", from:oh-my-zsh
zplug "plugins/jira", from:oh-my-zsh
zplug "plugins/npm", from:oh-my-zsh
zplug "plugins/docker", from:oh-my-zsh
zplug "plugins/docker-compose", from:oh-my-zsh
zplug "plugins/st", from:oh-my-zsh

# Configure theme
zplug "mafredri/zsh-async"
zplug "sindresorhus/pure"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

# Then, source plugins and add commands to $PATH
zplug load # --verbose

source "$DOTFILES_PATH/zsh/modules/editor/init.zsh"
source "$DOTFILES_PATH/zsh/modules/directory/init.zsh"
source "$DOTFILES_PATH/zsh/modules/completions/init.zsh"
source "$DOTFILES_PATH/zsh/modules/autosuggestions/init.zsh"
